# Generated by Django 5.1.7 on 2025-04-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_contactmessage_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
